language: node_js
node_js:
  - "11.10.1"
install: 
  - npm install
before_script:
  - export COVERAGE_TOKEN=$COVERAGE_TOKEN
  - export F_PRIVATE_KEY_ID=$F_PRIVATE_KEY_ID
  - export F_CLIENT_EMAIL=$F_CLIENT_EMAIL
  - export F_CLIENT_ID=$F_CLIENT_ID
script:
  - npm run write-firebase
  - npm run write-coveralls
  - npm test
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: pantry-managementbe
  on: master 
  strategy: git