language: node_js
node_js:
  - "11.10.1"
install: 
  - npm install
before_script:
  - export COVERAGE_TOKEN=$COVERAGE_TOKEN
  - export F_PRIVATE_KEY_ID=$F_PRIVATE_KEY_ID
  - export F_CLIENT_EMAIL=$F_CLIENT_EMAIL
  - export F_CLIENT_ID=$F_CLIENT_ID
  - export TW_NUMBER=$TW_NUMBER
  - export TW_SID=$TW_SID
  - export TW_TOKEN=$TW_TOKEN
script:
  - npm run write-coveralls
  - npm run write-twilio
  - npm test
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: pantry-managementbe
  on: master 
  strategy: git