language: node_js
node_js:
  - "11.10.1"
install: 
  - npm install
before_script:
  - export COVERAGE_TOKEN=$COVERAGE_TOKEN
  - export FIREBASE_ADMIN_KEY=$FIREBASE_ADMIN_KEY
script:
  - npm run write-firebase
  - npm run write-coveralls
  - npm test
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: pantry-managementbe
  on: master 
  strategy: git